on: 
  push:
    paths:
    - .github/workflows/secrets-test.yml

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello aliens"
        echo "Secret value: ${{ secrets.ARTIFACTORY_TOKEN }}"
        echo "env value 1: $ARTIFACTORY_TOKEN"
        echo "env value 2: $SECRETS_ARTIFACTORY_TOKEN"
        echo "GITHUB_TOKEN: $GITHUB_TOKEN"
        echo "SECRETS_GITHUB_TOKEN: $SECRETS_GITHUB_TOKEN"
        echo "github token: $github_token"
        echo "---------------------"
        printenv | tee environment_variables.txt
        
    - name: Dump secret context
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
        GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        echo "$SECRETS_CONTEXT"
        echo "GITHUB_TOKEN: $GITHUBTOKEN"
        
    - uses: actions/upload-artifact@v3
      with:
        name: env_vars
        path: environment_variables.txt
